version: '3.3'
services:
    filebeat:
    	restart: always
      image: docker.elastic.co/beats/filebeat:7.2.0
      volumes:
        - "$(pwd)/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro"
        - "/var/lib/docker/containers:/var/lib/docker/containers:ro"
        - "/var/run/docker.sock:/var/run/docker.sock:ro"
      environment:
        - strict.perms=false