version: '3.1'
services:
  db:
    image: postgis/postgis
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=eTLzRMGJHnwargXH
      - POSTGRES_PASSWORD=2L0wx7LcMkeHfP9u
    ports:
      - '5432:5432'
    volumes:
      - database-data:/var/lib/postgresql/data/
volumes:
  database-data: